import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root=process.cwd(), target=process.argv[2];
if(!target)throw new Error('Pass the checked-out piket-web directory');
const version=fs.readFileSync('app/build.gradle','utf8').match(/versionName "([^"]+)"/)[1];
const assets='app/src/main/assets';
const sourceHtml=fs.readFileSync(`${assets}/index.html`,'utf8');
const core=fs.readFileSync(`${assets}/assets/piket-core.js`);
const schedules=fs.readFileSync(`${assets}/assets/piket-schedules.js`);
const fingerprint=crypto.createHash('sha256').update(sourceHtml).update(core).update(schedules).digest('hex').slice(0,8);
const resourceVersion=`${version}-${fingerprint}`;
let html=sourceHtml.replaceAll('?v=1.5.0',`?v=${resourceVersion}`);
fs.writeFileSync(path.join(target,'index.html'),html);
for(const name of ['piket-core.js','piket-schedules.js'])fs.copyFileSync(`${assets}/assets/${name}`,path.join(target,'assets',name));
let sw=fs.readFileSync(path.join(target,'sw.js'),'utf8').replace(/const CACHE_VERSION = '[^']+';/,`const CACHE_VERSION = 'piket-web-v${resourceVersion}';`).replace(/\?v=[^']+/g,`?v=${resourceVersion}`);
fs.writeFileSync(path.join(target,'sw.js'),sw);
console.log(`Web synchronized to ${resourceVersion}`);
